### ISSUE TITLE
Function defs don't have return value when multiple expressions in cell

### ISSUE THREAD

**Issue by lockywolf** [Calysto/calysto_hy#4]
I am having the following issue:

If I run the following code in a separate cell:

```scheme
(def a '(+ (+ 2 3) (* 3 4)))
(def b "bbb")
a
```

Out[]: displays nothing.

Then I run it like this:

```scheme
(def a '(+ (+ 2 3) (* 3 4)))
(def b "bbb")
a
b
```

Out[]: displays ('+' ('+' 2 3) ('*' 3 4))

And the following code:
```
(def a '(+ (+ 2 3) (* 3 4)))
(def b "bbb")
a
b
a
```
Evaluates to:
'bbb'

This behaviour is not present in a raw Hy interpreter opened in console.

The version is... the last, I suppose. Python version is 3.5.2.

**Comment by dsblank** [comment]
It seems that evaluating a function is not properly setting the result displayhook, unless it is the only expression. I don't think that this a Calysto_hy issue.

**Comment by lockywolf** [comment]
Whos issue is it then? Metakernel?

**Comment by dsblank** [comment]
If it is an issue with the Jupyter component, it would be here, specifically in these lines:

https://github.com/Calysto/calysto_hy/blob/master/calysto_hy/kernel.py#L76-L102

But it appears (to me) that there might be something that Hy is doing wrong itself in handling the reference to a function definition in a list of expressions. 

Some things you could try:

1. change the compile mode in the lines above from "single" to "exec" (or something else) (unlikely)
2. does eval() give a return value different from self.result? (maybe)
3. check on the hy mailing list for ideas (most helpful, probably because it is a hy bug)

**Comment by tuturto** [comment]
Out of interest, what does
```clj
(do (def a '(+ (+ 2 3) (* 3 4)))
    (def b "bbb")
    a
    b
    a)
```
evaluate to?

**Comment by dsblank** [comment]
'bbb'

![screenshot from 2017-08-05 06-39-55](https://user-images.githubusercontent.com/168568/28994932-f68fc170-79a8-11e7-80e8-a39597fa1049.png)

**Comment by dsblank** [comment]
Looks like this has been fixed by hy.
